### ISSUE TITLE
Decide on frontend framework to use

### ISSUE THREAD

**Issue by dr-hextanium** [dr-hextanium/cookbook#1]
I haven't made a website in a while.

This entire site will be purely static, so hosting is pretty simple; I'll probably use GitHub Pages on my robotic team's account.

I've been looking at [`Astro`](https://astro.build/) since it seems to excel with static sites. 
The vision for Cookbook is to have a robustly searchable "hand book" of common problems easily available and reference-able. 

For fast searching, [`PageFind`](https://pagefind.app/) looks like a great option, which seems to work with a lot of libraries.

My initial thought was to just use `SvelteKit` since I'm most familiar with that, but I do not think that it's the best option for something like this.

Any external ideas are very welcome, and if you would like to contribute, hit me up at [`hextanium`](https://discord.com/users/280024224121356288) on Discord.

This is mostly for my own reference though.

**Comment by Froze-N-Milk** [comment]
[mdbook](https://rust-lang.github.io/mdBook/)

I loved using md book while learning rust!. The whole thing is super clean and easy to follow and use.

**Comment by schsdrobotics** [comment]
Decided on `mdbook` as per suggestion. Initial revision released.
