### ISSUE TITLE
Using a PID Controller with Roadrunner 0.5.6

### ISSUE THREAD

**Issue by Vivexplorer** [dr-hextanium/cookbook#10]
To use a PID(f) controller with Roadrunner trajectories, you need to use async trajectories so that the PID controller can run in the background. You can do this by "
                 drive.followTrajectoryAsync(trajectory); "
You will also need to add another line of code inside of your loop:
                 drive.followTrajectoryAsync(trajectory);

For more information, consider looking at the roadrunner page on async following. 
[](https://learnroadrunner.com/advanced.html#async-following)

**Comment by RuckusRoboticsCode** [comment]
this is being review rn already

**Comment by Vivexplorer** [comment]
Okay
